export { default as Pokemons } from "./Pokemons/Pokemons"
export { default as TypesSelection } from "./TypesSelection/TypesSelection"
export { default as SearchInput } from "./SearchInput/SearchInput"
export { default as Loading } from "./Loading/Loading"
export { default as Pagination } from "./Pagination/Pagination"